apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-uppy
  namespace: uppy
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_SERVER_IP
    path: "/"
